/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-25 06:26:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/임베디드웹/project/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MovieProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1690855704120L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/default.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/header.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/main.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/footer.css\" />\n");
      out.write(" <!-- Swiper -->\n");
      out.write(" <link href=\"https://hangeul.pstatic.net/hangeul_static/css/NanumBarunGothicYetHangul.css\" rel=\"stylesheet\">\n");
      out.write(" <!-- Swiper -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css\"/>\n");
      out.write("    <style>\n");
      out.write("        .swiper-slide{\n");
      out.write("            width:300px;\n");
      out.write("            height:380px;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("    <header>\n");
      out.write("        <div id=\"header_section\" class=\"header\">\n");
      out.write("            <h1 class=\"logo\">\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main.do\"></a>\n");
      out.write("            </h1>\n");
      out.write("            <div class=\"gnb\">\n");
      out.write("                <ul class=\"menu1\">\n");
      out.write("                    <li><a href=\"\"><img src=\"resources/image/페이스북.png\" alt=\"페이스북로고\"></a></li>\n");
      out.write("                    <li><a href=\"\" style=\"width:35px\"><img src=\"resources/image/유튜브-removebg-preview.png\" alt=\"유튜브로고\"></a></li>\n");
      out.write("                    <li><a href=\"\"><img src=\"resources/image/인스타그램.png\" alt=\"인스타그램로고\"></a></li>\n");
      out.write("                </ul>\n");
      out.write("                <ul class=\"menu2\">\n");
      out.write("                    <li><a href=\"\">멤버십</a></li>\n");
      out.write("                    <li><a href=\"\">고객센터</a></li>\n");
      out.write("                    <li><a href=\"\">단체관람/대관문의</a></li>\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login.do\">로그인</a></li>\n");
      out.write("                </ul>\n");
      out.write("                <ul class=\"menu3\">\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/join.do\">회원가입</a></li>\n");
      out.write("                    <li><a href=\"\">바로예매</a></li>\n");
      out.write("                    <li><a href=\"\"><img src=\"resources/image/햄버거버튼.png\"></a></li>\n");
      out.write("                </ul>\n");
      out.write("                <div class=\"nav\">\n");
      out.write("                    <ul class=\"submenu\">\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"\">예매</a>\n");
      out.write("                            <ul class=\"submenu1\">\n");
      out.write("                                <li><a href=\"\">예매하기</a></li>\n");
      out.write("                                <li><a href=\"\">상영시간표</a></li>\n");
      out.write("                                <li><a href=\"\">할인안내</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"\">영화</a>\n");
      out.write("                            <ul class=\"submenu2\">\n");
      out.write("                                <li><a href=\"\">홈</a></li>\n");
      out.write("                                <li><a href=\"\">현재상영작</a></li>\n");
      out.write("                                <li><a href=\"\">상영예정작</a></li>\n");
      out.write("                                <li><a href=\"\">아르떼</a></li>\n");
      out.write("                                <li><a href=\"\">국립극장</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"\">영화관</a>\n");
      out.write("                            <ul class=submenu3>\n");
      out.write("                                <li><a href=\"\">스페셜관</a></li>\n");
      out.write("                                <li><a href=\"\">서울</a></li>\n");
      out.write("                                <li><a href=\"\">경기/인천</a></li>\n");
      out.write("                                <li><a href=\"\">충청/대전</a></li>\n");
      out.write("                                <li><a href=\"\">전라/광주</a></li>\n");
      out.write("                                <li><a href=\"\">경상/대구</a></li>\n");
      out.write("                                <li><a href=\"\">경상/부산/울산</a></li>\n");
      out.write("                                <li><a href=\"\">강원</a></li>\n");
      out.write("                                <li><a href=\"\">제주</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"\">이벤트</a>\n");
      out.write("                            <ul class=\"submenu4\">\n");
      out.write("                                <li><a href=\"\">홈</a></li>\n");
      out.write("                                <li><a href=\"\">영화</a></li>\n");
      out.write("                                <li><a href=\"\">시사회/무대인사</a></li>\n");
      out.write("                                <li><a href=\"\">HOT</a></li>\n");
      out.write("                                <li><a href=\"\">제휴할인</a></li>\n");
      out.write("                                <li><a href=\"\">우리동네영화관</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"\">스토어</a>\n");
      out.write("                            <ul class=\"submenu5\">\n");
      out.write("                                <li><a href=\"\">베스트</a></li>\n");
      out.write("                                <li><a href=\"\">관람권</a></li>\n");
      out.write("                                <li><a href=\"\">스낵음료</a></li>\n");
      out.write("                                <li><a href=\"\">포토카드</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"\"></a>\n");
      out.write("                            <ul></ul>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("    <main>\n");
      out.write("        <div class=\"subsection\">\n");
      out.write("            <div class=\"sub1\">\n");
      out.write("                <div class=\"sub2\">\n");
      out.write("                    <div class=\"front\">\n");
      out.write("                        <a href=\"\"><img src=\"https://caching2.lottecinema.co.kr/lotte_image/2023/BIG/BIG_1920774.jpg\" alt=\"\"></a>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"back\">\n");
      out.write("                        <a href=\"\"><img src=\"resources/image/메인화면2.jpg\" alt=\"\"></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("    </main>\n");
      out.write("    <div class=\"contents\">\n");
      out.write("        <div class=\"contentslist\">\n");
      out.write("            <div class=\"mainmovie swiper-container\">\n");
      out.write("                <ul class=\"swiper-wrapper\">\n");
      out.write("                    <li class=\"swiper-slide\"><a href=\"\"><img src=\"resources/image/분노의질주.jpg\" alt=\"\">분노의질주:라이드 오어 다이</a></li>\n");
      out.write("                    <li class=\"swiper-slide\"><a href=\"\"><img src=\"resources/image/가디언즈.jpg\" alt=\"\">가디언즈 오브 갤럭시:Volume 3</a></li>\n");
      out.write("                    <li class=\"swiper-slide\"><a href=\"\"><img src=\"resources/image/범죄도시.jpg\" alt=\"\">범죄도시3</a></li>\n");
      out.write("                    <li class=\"swiper-slide\"><a href=\"\"><img src=\"resources/image/슈퍼마리오.jpg\" alt=\"\">슈퍼마리오브라더스</a></li>\n");
      out.write("                    <li class=\"swiper-slide\"><a href=\"\"><img src=\"resources/image/빅트립2.jpg\" alt=\"\">빅트립2</a></li>\n");
      out.write("                    <li class=\"swiper-slide\"><a href=\"\"><img src=\"resources/image/더문.jpg\" alt=\"\">더문</a></li>\n");
      out.write("                    <li class=\"swiper-slide\"><a href=\"\"><img src=\"resources/image/엘리멘탈.jpg\" alt=\"\">엘리멘탈</a></li>\n");
      out.write("                    <li class=\"swiper-slide\"><a href=\"\"><img src=\"resources/image/미션.jpg\" alt=\"\">미션임파서블</a></li>\n");
      out.write("                    <li class=\"swiper-slide\"><a href=\"\"><img src=\"resources/image/코난.jpg\" alt=\"\">코난</a></li>\n");
      out.write("                    <li class=\"swiper-slide\"><a href=\"\"><img src=\"resources/image/밀수.jpg\" alt=\"\">밀수</a></li>\n");
      out.write("                </ul>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("         </div>\n");
      out.write("    </div>\n");
      out.write("     <!-- 오른쪽 사이드 배너 -->\n");
      out.write("    <div class=\"quick_section\">\n");
      out.write("        <div class=\"quick_menu\">\n");
      out.write("            <!-- 퀵메뉴 이미지 -->\n");
      out.write("            <a href=\"#none\"><img src=\"resources/image/961c9cbf311b4f1299827c21a61fab76.png\" alt=\"\"></a>\n");
      out.write("            <a href=\"#none\"><img src=\"resources/image/c1dbce4f91e948498c7c78239b7157ac.png\" alt=\"\"></a>\n");
      out.write("            <a href=\"#none\"><img src=\"resources/image/c793af89f3b648aa99cc679186ccfa02.png\" alt=\"\"></a>\n");
      out.write("            <!-- 최상단 올라가기 버튼 -->\n");
      out.write("            <a href=\"#none\" class=\"quick_top\" id=\"to_top\">TOP</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("          <!-- 왼쪽 사이드 배너 -->\n");
      out.write("          <div class=\"left_section\">\n");
      out.write("            <div class=\"left_banner\">\n");
      out.write("              <!-- 광고 배너 이미지 -->\n");
      out.write("              <a href=\"\"><img src=\"resources/image/RUBYGILLMAN_145145.png\" alt=\"\"></a>\n");
      out.write("            </div>\n");
      out.write("            <!-- 광고 닫는 버튼 -->\n");
      out.write("            <button class=\"banner_close\"></button>\n");
      out.write("          </div>\n");
      out.write("    <footer>\n");
      out.write("        <div class=\"footer\">\n");
      out.write("            <div class=\"inner\">\n");
      out.write("                <span class=\"footerlogo\">\n");
      out.write("                    <img src=\"resources/image/logo3.png\" alt=\"\">\n");
      out.write("                </span>\n");
      out.write("                <ul class=\"footermenu\">\n");
      out.write("                    <li><a href=\"#\" >이용약관</a></li>\n");
      out.write("                    <li><a href=\"#\">개인정보처리방침</a></li>\n");
      out.write("                    <li><a href=\"#\">이메일무단수집거부</a></li>\n");
      out.write("                    <li><a href=\"#\">영상정보처리기기 운영 및 관리방침</a></li>\n");
      out.write("                    <li><a href=\"#\">L.POINT회원안내</a></li>\n");
      out.write("                    <li><a href=\"#\">배정기준</a></li>\n");
      out.write("                    <li><a href=\"#\">채용안내</a></li>\n");
      out.write("                    <li><a href=\"#\">광고/임대문의</a></li>\n");
      out.write("                    <li><a href=\"#\">기업정보</a></li>\n");
      out.write("                    <li><a href=\"#\">사회적책임</a></li>\n");
      out.write("                </ul>\n");
      out.write("                <div class=\"address\">\n");
      out.write("                    <span class=\"bar\">서울특별시 송파구 올림픽로 300 롯데월드타워 27층</span>\n");
      out.write("                    <span class=\"bar\">고객센터 1544-8855 (유료)</span><br>\n");
      out.write("                    <span class=\"bar\">대표이사 3조</span>\n");
      out.write("                    <span class=\"bar\">사업자등록번호 111-11-11111</span>\n");
      out.write("                    <span class=\"bar\">통신판매없신고번호 제1111호</span>\n");
      out.write("                    <span class=\"bar\">개인정보보호책임자 4조</span>\n");
      out.write("                </div>\n");
      out.write("                <p class=\"copyright\" style=\"font-size: 12px;\">COPYRIGHT LOTTE CINEMA ALL RIGHT RESERVED.</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("<script src=\"https://unpkg.com/swiper/swiper-bundle.min.js\"></script>\n");
      out.write("<!-- 제이쿼리 -->\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\n");
      out.write("<!-- lodash cdn -->\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.21/lodash.min.js\" integrity=\"sha512-WFN04846sdKMIP5LKNphMaWzU7YpMyCU245etK3g/2ARYbPK9Ub18eG+ljU96qKRCWh+quCY7yefSmlkQw1ANQ==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\n");
      out.write("<!-- Swiper -->\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("     document.addEventListener(\"DOMContentLoaded\", function(){\n");
      out.write("         var swiper = new Swiper('.mainmovie.swiper-container', {\n");
      out.write("             direction: 'horizontal',\n");
      out.write("             autoplay: {\n");
      out.write("                 delay: 1000,\n");
      out.write("             },\n");
      out.write("             loop: true,\n");
      out.write("             slidesPerView: 5,\n");
      out.write("             spaceBetween: 10,\n");
      out.write("             centeredSlides: true,\n");
      out.write("     })\n");
      out.write(" });\n");
      out.write("     // TOP 누르면 최상단 이동\n");
      out.write("     const toTopBtn_el = document.getElementById('to_top');\n");
      out.write("        toTopBtn_el.addEventListener('click',function(){\n");
      out.write("            window.scrollTo({top:0,behavior:'smooth'})\n");
      out.write("        })\n");
      out.write("     // 우측 퀵메뉴\n");
      out.write("     $(window).scroll(function(){\n");
      out.write("    var scrollTop = $(document).scrollTop();\n");
      out.write("    if (scrollTop < 200) {\n");
      out.write("      scrollTop = 200;\n");
      out.write("    }\n");
      out.write("      $(\".quick_section\").stop();\n");
      out.write("      $(\".quick_section\").animate( { \"top\" : scrollTop });\n");
      out.write("    });\n");
      out.write("    // 좌측 광고\n");
      out.write("    $(window).scroll(function(){\n");
      out.write("    var scrollTop = $(document).scrollTop();\n");
      out.write("    if (scrollTop < 300) {\n");
      out.write("      scrollTop = 300;\n");
      out.write("    }\n");
      out.write("      $(\".left_section\").stop();\n");
      out.write("      $(\".left_section\").animate( { \"top\" : scrollTop });\n");
      out.write("    });\n");
      out.write("     // x표시 광고 끄기\n");
      out.write("    // 버튼과 광고 요소 선택\n");
      out.write("    const bannerCloseButton = document.querySelector('.banner_close');\n");
      out.write("    const leftBanner = document.querySelector('.left_banner');\n");
      out.write("\n");
      out.write("    // 버튼 클릭 시 광고 숨기기\n");
      out.write("    bannerCloseButton.addEventListener('click', function () {\n");
      out.write("      leftBanner.style.display = 'none';\n");
      out.write("      bannerCloseButton.style.display = 'none';\n");
      out.write("    });\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
